### ISSUE TITLE
UCloud Web Qualification

### ISSUE THREAD

**Issue by JV-conseil** [JV-conseil/ucloud#3]
> Validate UCloud as a stable cloud service to serve Python Django v4.1.2 web app coupled with a PostgreSQL Server
> Provided UCloud is up and running 👉 <https://status.cloud.sdu.dk/>

<img width="2560" alt="app-thalassa cloud sdu dk running in DEBUG=False with cache activated and collectstatic" src="https://user-images.githubusercontent.com/8126807/224797118-8913abc9-6ab7-4880-97a2-1f09eef19f52.png"><br>_[app-thalassa.cloud.sdu.dk](https://app-thalassa.cloud.sdu.dk/) running in DEBUG=False with cache activated and collectstatic._

- [x] PostgreSQL Server v14.5 initialization.
- [x] PostgreSQL Server v14.5 New Database and User creation.
- [x] PostgreSQL Server v14.5 SSL set up `pg_hba.conf`
- [x] Django v4.1.2 access environment variables through `os.environ.get("DBHOST")`
- [x] Django v4.1.2 `DEBUG=True`
- [x] Django v4.1.2 `SECURE_SSL_REDIRECT = True` fails 👉 should not be declared in `settings.py` 🚫
- [x] Django v4.1.2 `SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")` ✅
- [x] Django v4.1.2 <> PostgreSQL Server v14.5 connection `django.db.backends.postgresql`
- [x] Django v4.1.2 <> PostgreSQL Server v14.5 SSL transactions `SSLMODE=require`
- [x] Django v4.1.2 `makemigrations` & `migrate`
- [x] Django v4.1.2 `create_superuser`
- [x] Django v4.1.2 `CSRF_COOKIE_SECURE = True` and `CSRF_USE_SESSIONS = True`
- [x] Django v4.1.2 `DEBUG=False`
- [x] Django v4.1.2 `ALLOWED_HOSTS` set to 
`['localhost', 'app-627236-0.cloud.sdu.dk', 'app-githubbing.cloud.sdu.dk']`
- [x] Django v4.1.2 `collectstatic`
- [x] Django v4.1.2 serves static files through `whitenoise`
- [x] Django v4.1.2’s cache framework > Filesystem caching `django.core.cache.backends.filebased.FileBasedCache`
- [x] Django v4.1.2 <> PostgreSQL Server v14.5 ETL `python manage.py xloader`.
- [x] Django v4.1.2 run in pseudo UCloud localhost mode (see below 👀 ) <https://app-{job-id}-0.cloud.sdu.dk>.
- [x] Django v4.1.2 run with a Public link <https://app-githubbing.cloud.sdu.dk>.
- [x] UCloud app run over 24 hours ⏳
- [x] PostgreSQL Server v15.2 initialization.
- [x] PostgreSQL Server v15.2 New Database and User creation.
- [x] PostgreSQL Server v15.2 SSL set up `pg_hba.conf`
- [x] Django v4.1.2 <> PostgreSQL Server v15.2 connection `django.db.backends.postgresql`
- [x] Django v4.1.2 <> PostgreSQL Server v15.2 SSL transactions `SSLMODE=require`
- [x] Django v4.1.2 <> PostgreSQL Server v15.2 ETL `python manage.py xloader`

### Issues

- [x] [Public Link running only once](https://github.com/JV-conseil/ucloud/issues/4) then error 503 **_upstream connect error or disconnect/reset before headers. reset reason: connection termination_** 🙅 (Solved on 2023, March 24th).
- [ ] Outdated Python 🐍 versions in containerized app.

### End of March, 2023 👀

- [x] PostgreSQL server v14.5 version bump to `v15.2`
- [ ] Django v4.1.2 version bump to `v4.1.7`
- [ ] Python version bump to `v3.11.2`

### TODO

- [ ] [Python 3.11.2](https://www.python.org/downloads/) - Always run latest stable release of Python 🐍 in containerized app (at least Django).
- [ ] [PgBouncer](https://www.pgbouncer.org/2022/12/pgbouncer-1-18-0) - 1.18.0 Dec 12, 2022. Install, setup with PostgreSQL Server v15.2.
- [ ] Custom Domain Name (DNS) instead of Public Links.
- [ ] PenTest
- [ ] ...

### Pseudo UCloud localhost mode

> Pseudo UCloud localhost mode = when Django app is running on <https://app-{job-id}-0.cloud.sdu.dk> interface with no Public link connected.

1. Pseudo UCloud localhost execution is cookie restricted to the current browser session 👉 cannot be shared with another browser session; an error 403 is raised: same browser in Private mode will fail, another browser on the same computer will fail.
2. Public link and Pseudo UCloud localhost mode are exclusive to one another.
3. Public link resources cannot be shared among users 👉 one user has to launch a job and attach a Public link he "owns", he cannot attach a Public link created by another user.
4. As an extra-check/validation, UCloud does check your Public link availability on creation for a similar one already existing created by someone else.

### Containers overview

> March 2022 with u1-standard-8 machine.

| Environment                                                        | set -eufo pipefail | ${USER} | Python 3.11.0 | apt update |   Creation |      Age |
| :----------------------------------------------------------------- | -----------------: | ------: | ------------: | ---------: | ---------: | -------: |
| Terminal Debian 0.9.0                                              |                  ❌ |       ✅ |       3.6.8 ❌ |            | 28/12/2022 |  75 days |
| Terminal Ubuntu 0.20.0                                             |                  ❌ |       ✅ |      3.10.7 ❌ |    960 sec | 28/12/2022 |  75 days |
| Terminal Ubuntu 0.21.0<br>(Linux version 5.4.228.el8 Ubuntu 22.10) |                  ❌ |       ✅ |      3.10.7 ❌ |    233 sec | 21/03/2023 |   0 days |
| Terminal CentOS 0.8.0                                              |                  ❌ |       ✅ |       3.6.8 ❌ |            | 14/06/2022 | 272 days |
| PostgreSQL Server v14.5<br>(Linux v5.4.228.el8 Debian)              |                  ✅ |       ❌ |             ❌ |    218 sec | 12/10/2022 | 152 days |
| PostgreSQL Server v15.2<br>(Linux v5.4.228.el8 Debian 6.1.2023)     |                  ✅ |       ❌ |       3.9.2 ❌ |     24 sec | 16/03/2023 |   4 days |
| Django v4.1.2 4.1.2<br>(Linux v5.4.228.el8 Debian)                        |                  ✅ |       ❌ |             ✅ |    962 sec | 08/11/2022 | 125 days |

### Incident review

> Health Page Status 👉 <https://status.cloud.sdu.dk/>

Year | Incidents (nb)
--: | --:
2023 | 9
2022 | 18

[Service Level Objective](https://legal.cloud.sdu.dk/terms/sla-ucloud-compute#ucloud-compute-service-level-agreement-sla) (SLO) for UCloud Compute **>= 85%** for Monthly Uptime Percentage.

## Notes 📝

- [Aalborg](https://www.claaudia.aau.dk/platforms-tools/UCloud/) (AAU) presentation of UCloud 🎓
